[ 2025-08-06 01:45:28,971 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-08-06 01:45:28,971 ] root - INFO - Getting the data from mongodb
[ 2025-08-06 01:45:28,971 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-08-06 01:45:28,971 ] root - INFO - Exporting data from mongodb
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\pipline\training_pipeline.py] at line number [50]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-08-06 01:45:28,971 ] root - ERROR - Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\pipline\training_pipeline.py] at line number [136]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\pipline\training_pipeline.py] at line number [50]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\VARDAN\OneDrive\Desktop\MLOPS\PROJECT-MLOPS\ML-OPS-PROJECT\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
